### ISSUE TITLE
Comment Syntax in Calculator Module

### ISSUE THREAD

**Issue by austin-18** [stevepwang/accol-syntax#1]
Comment syntax in the Calculator Module is not processed due to requirement of a preceding colon and missing the #comments in the included patterns in the comments syntax.

The calculator **_:C_** comment syntax is being interpreted as a keyword.operator.accol scope due to the colon and regex match. Proposing to update the regex match for keyword.operator.accol to the following:
`"match": "\\+|-|\\*|/|(<|>|!|=)=?|&|\\||\\^|~|:\\w{1,3}[^\\s]"`

Additionally, adding the comments patter inclusion to the _**CALCULATOR**_ syntax:

`
"begin": "CALCULATOR",
                "beginCaptures": {
                  "0": { "name": "entity.name.function.accol"}
                },
                "end": "^(?=\\s*\\d+\\s+\\*)",
                "patterns": [
                  { "include": "#line_numbers" },
                  { "include": "#grammar" },
                  { "incude": "#comments" },
                  { "include": "#keywords" },
                  { "include": "#operators" },
                  { "include": "#variables" },
                  { "include": "#constants" }
                ]
`

**Comment by stevepwang** [comment]
Can you create a pull request?

**Comment by stevepwang** [comment]
Changes made

**Comment by austin-18** [comment]
@stevepwang Could not open a pull request on the master branch and could not create a new branch due to not being able to contribute to this repository.

Thanks for implementing the fix
